### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by michijeran** [OpenReqEU/similarity-detection#2]
Hi,

will there be a docker container ready version?

The database one directory above the two services isn't available in both docker containers ...

Best regards,
Michi
#opencall

**Comment by FerranAgulloLopez** [comment]
We greatly apologize for the answer delay. We have not in mind making a docker container version in the nearer future. Nevertheless, we have changed the database location to the CompareAPI directory in the last commit.

BR,
Ferran Agulló
