### ISSUE TITLE
Service via api.openreq.eu

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/similarity-detection#4]
Hi,

Will the similarity-detection service at api.openreq.eu be updated to the most recent version?

**Comment by LloydThinks** [comment]
Hi @AndreaMussmann , are you asking about updating documentation, or the deployment of the most recent code to the host at api.openreq.eu?

**Comment by AndreaMussmann** [comment]
Hi, I wanted to know whether the most recent code will be deployed to the host at api.openreq.eu.

**Comment by FerranAgulloLopez** [comment]
Hi, I don't clearly know what are you asking for but maybe this can help. The last commit of the master branch is deployed in the url 'https://api.openreq.eu/similarity-detection' and the corresponding swagger is available at 'https://api.openreq.eu/similarity-detection/swagger-ui.html#/'.

**Comment by AndreaMussmann** [comment]
Yes, this helps. Thank you! I was only ever checking the website api.openreq.eu (not api.openreq.eu/similarity-detection/swagger-ui.html#). On this website, the api of the similarity detection service is out of date, therefore I assumed that the service was not up-to-date with the most recent master branch commit.
