### ISSUE TITLE
main.db file

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/similarity-detection#5]
Hi,

I am trying to run the most recent version (at commit 0325322) of the similarity-detection service locally (fresh clone, downloaded today, 7.8.). When I add a new model to the service using http://localhost:9404/upc/similarity-detection/BuildModel<options>, the service throws the following error:
``Aug 07, 2019 10:41:45 AM upc.similarity.compareapi.config.Control showInfoMessage
INFO: BuildModel: Start computing
2019-08-07 10:41:45.085  INFO 9156 --- [nio-9405-exec-1] CompareComponent.Control                 : BuildModel: Start computing
Aug 07, 2019 10:41:45 AM upc.similarity.compareapi.config.Control showErrorMessage
SEVERE: path to 'data/main.db': '<path to git>/openReq/testSimilarity/similarity-detection/ComparerAPI/data' does not exist
2019-08-07 10:41:45.434 ERROR 9156 --- [nio-9405-exec-1] CompareComponent.Control                 : path to 'data/main.db': '<path to git>/openReq/testSimilarity/similarity-detection/ComparerAPI/data' does not exist
``

There is no ComparerAPI/data directory in the git clone and I cannot find the file main.db in the clone. Do I have to download the main.db file separately?

**Comment by LloydThinks** [comment]
@quim-motger , do you have an update on this?

**Comment by FerranAgulloLopez** [comment]
Hello, as you said, the data directory was missing. I have just pushed a new commit that adds the directory and a default database file inside it that should solve your issue. Anyways, the database file can be created at any time with the method clearDatabase exposed in the api.

I am at your disposal to solve any other problem you may encounter.

**Comment by AndreaMussmann** [comment]
Thanks, this solved my issue.
